In [1]:
pip install NeuralNMF

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 MB 22.9 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [12]:
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import csv
import pandas as pd
import re
import nltk 
from nltk.corpus import stopwords

In [28]:
df = pd.read_csv('text_of_tweets.csv')


# Remove hashtags from text column (assuming column name is 'text')
#df['text_clean'] = df['text'].apply(lambda x: re.sub(r'#\w+', '', x).strip())

# Remove multiple spaces created by removing hashtags
#df['text_clean'] = df['text_clean'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

#print("Original text with hashtags:")
#print(df['text'].head())
#print("\nClean text without hashtags:")
#print(df['text_clean'].head())
df

Unnamed: 0                                               text
0              0  Anyone feel like looking through the list of i...
1              1  "If you think that your right to speech is mor...
2              2  I ran at elevation to make it to user308 s #Di...
3              3  user172 user308 user36 Here!!! #disruptJMM you...
4              4  user308 user36 Where and what? - let's get the...
...          ...                                                ...
1124        1124  RT user266  AMS-AWM invited session on Mathema...
1125        1125  RT user266  AMS-AWM invited session on Mathema...
1126        1126  RT user246  “[C]arry some of this weight with ...
1127        1127  RT user75  Kelly MacArthur now speaking about ...
1128        1128  RT user75  The stereotype of a mathematician i...

[1129 rows x 2 columns]

In [6]:
type(df["text"])

nltk.download('stopwords')

pandas.core.frame.DataFrame

In [31]:
groupNum=4
documents=df["text"]


#documents=["I write something does this have to be really long", "I am so very lost bro, what's going on something else"]

#vectorizer=TfidfVectorizer(stop_words='english')
stopwords_list=stopwords.words("english")
#stopwords_list+= ["rt", "https://t.co/pIPCd6Nu9s","https://t.co/DdGBGsLBKe","pipcd6nu9s", "ddgbgslbke", "https"]
stopwords_list+= ["rt", "RT"]

vectorizer=TfidfVectorizer(stop_words=stopwords_list, preprocessor=lambda s: re.sub(r'http.*\s?', '',s).lower())
X=vectorizer.fit_transform(documents)
names=vectorizer.get_feature_names_out()
print(names)
n=len(names)
print(X)

nmf=NMF(n_components=groupNum, max_iter=10000,l1_ratio=0)
W=nmf.fit_transform(X)
H=nmf.components_

print("Document-Topic Matrix:\n", W)
print("Topic-Word Matrix:\n", H)

for i in range(groupNum):
    print("*********************************************")
    print("Names in Group:", i+1)
    for j in range(n):
        if H[i,j]>.1:
            print(names[j])


['00' '10' '11' ... 'yore' 'yt' '春节快乐']
  (0, 93)	0.20844361686195892
  (0, 552)	0.2443122815321362
  (0, 848)	0.18591668295128036
  (0, 861)	0.2517803855866228
  (0, 852)	0.24789056739634663
  (0, 773)	0.21507868983383877
  (0, 1445)	0.2517803855866228
  (0, 787)	0.11160903261423519
  (0, 1267)	0.2013326761550325
  (0, 993)	0.2870281415549899
  (0, 844)	0.271986248508198
  (0, 1104)	0.2870281415549899
  (0, 608)	0.2560411993324567
  (0, 671)	0.2116381689719567
  (0, 419)	0.05992101213489889
  (0, 179)	0.3098644518414129
  (0, 1442)	0.12536211478983486
  (0, 1424)	0.271986248508198
  (0, 1487)	0.19083424083801917
  (1, 787)	0.10270189633549034
  (1, 419)	0.055138920501772465
  (1, 1471)	0.16940001303249466
  (1, 1244)	0.20920349544224195
  (1, 1355)	0.22176597351779717
  (1, 719)	0.16121988971151957
  :	:
  (1126, 1710)	0.41557560532596416
  (1126, 1472)	0.4086599594993448
  (1126, 1608)	0.391161394548689
  (1127, 1662)	0.18012412293640256
  (1127, 175)	0.2890664199591968
  (1127, 807)

In [51]:
import torch
from NeuralNMF import Neural_NMF
X = 10*torch.mm(torch.randn(100,5),torch.randn(5,20)) #produce random low rank data
m, k1, k2, = X.shape[0], 10, 5
net = Neural_NMF([m, k1, k2])

In [3]:
from NeuralNMF import train
history = train(net, X, epoch=6, lr=500, supervised=False)
epoch =  1 
tensor(485.2435, dtype=torch.float64)
epoch =  2 
tensor(475.1584, dtype=torch.float64)
epoch =  3 
tensor(461.2400, dtype=torch.float64)
epoch =  4 
tensor(444.1705, dtype=torch.float64)
epoch =  5 
tensor(430.4947, dtype=torch.float64)
epoch =  6 
tensor(422.7317, dtype=torch.float64)

100%|██████████| 6/6 [00:00<00:00, 48.00it/s]


NameError: name 'tensor' is not defined

Tutorial time!!!! from Medium article

In [11]:
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "Mango, pineapple and banana smoothie.",
  "Strawberry, blueberry and raspberry smoothie.",
    "Mango, pineapple and coconut smoothie."
]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)

print(X.toarray())
print(X.shape)
print(vectorizer.get_feature_names_out())
nmf = NMF(n_components=2, random_state=42)
print(nmf)
W = nmf.fit_transform(X)
H = nmf.components_

print("Document-Topic Matrix:\n", W)
print("Topic-Word Matrix:\n", H)

[[0.63174505 0.         0.         0.4804584  0.4804584  0.
  0.37311881 0.        ]
 [0.         0.54645401 0.         0.         0.         0.54645401
  0.32274454 0.54645401]
 [0.         0.         0.63174505 0.4804584  0.4804584  0.
  0.37311881 0.        ]]
(3, 8)
['banana' 'blueberry' 'coconut' 'mango' 'pineapple' 'raspberry' 'smoothie'
 'strawberry']
NMF(n_components=2, random_state=42)
Document-Topic Matrix:
 [[6.27920439e-01 2.89477799e-17]
 [1.81158550e-17 8.23117356e-01]
 [6.27920439e-01 1.14221590e-17]]
Topic-Word Matrix:
 [[0.50304546 0.         0.50304546 0.76515808 0.76515808 0.
  0.59421351 0.        ]
 [0.         0.66388348 0.         0.         0.         0.66388348
  0.39210028 0.66388348]]


In [27]:
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "Mango, pineapple and banana.",
  "Strawberry, blueberry and raspberry.",
    "Mango, pineapple and coconut."
]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)

print(X)
print(X.toarray())
print(X.shape)
print(vectorizer.get_feature_names_out())
nmf = NMF(n_components=2, random_state=42) ##Pick the rank, n_components is 
#2 in this case
print(nmf)
W = nmf.fit_transform(X)
H = nmf.components_

print("Document-Topic Matrix:\n", W)
print("Topic-Word Matrix:\n", H)

  (0, 3)	0.5178561161676974
  (0, 4)	0.5178561161676974
  (0, 0)	0.680918560398684
  (1, 6)	0.5773502691896257
  (1, 1)	0.5773502691896257
  (1, 5)	0.5773502691896257
  (2, 3)	0.5178561161676974
  (2, 4)	0.5178561161676974
  (2, 2)	0.680918560398684
[[0.68091856 0.         0.         0.51785612 0.51785612 0.
  0.        ]
 [0.         0.57735027 0.         0.         0.         0.57735027
  0.57735027]
 [0.         0.         0.68091856 0.51785612 0.51785612 0.
  0.        ]]
(3, 7)
['banana' 'blueberry' 'coconut' 'mango' 'pineapple' 'raspberry'
 'strawberry']
NMF(n_components=2, random_state=42)
Document-Topic Matrix:
 [[0.52010624 0.        ]
 [0.         0.80515326]
 [0.52010624 0.        ]]
Topic-Word Matrix:
 [[0.65459564 0.         0.65459564 0.99567372 0.99567372 0.
  0.        ]
 [0.         0.71706878 0.         0.         0.         0.71706878
  0.71706878]]


In [20]:
import numpy as np
X2=np.array([[1,1,1,0,0,0,0],[0,0,0,1,1,1,0],[1,1,0,0,0,0,1]])

In [21]:
nmf = NMF(n_components=2, random_state=42)
print(nmf)
W2 = nmf.fit_transform(X2)
H2 = nmf.components_

print("Document-Topic Matrix:\n", W2)
print("Topic-Word Matrix:\n", H2)

NMF(n_components=2, random_state=42)
Document-Topic Matrix:
 [[5.29056791e-01 2.71050543e-20]
 [0.00000000e+00 9.33743230e-01]
 [5.29056791e-01 2.71050543e-20]]
Topic-Word Matrix:
 [[1.89015625 1.89015625 0.94507813 0.         0.         0.
  0.94507813]
 [0.         0.         0.         1.07095823 1.07095823 1.07095823
  0.        ]]


In [46]:
Rachel=np.array([[np.log(3/2)+1,np.log(3/2)+1,np.log(3)+1,0,0,0,0],[
    0,0,0,np.log(3)+1,np.log(3)+1,np.log(3)+1,0],
              [np.log(3/2)+1,np.log(3/2)+1,0,0,0,0,np.log(3)+1]])

Rachel

array([[1.40546511, 1.40546511, 2.09861229, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.09861229, 2.09861229,
        2.09861229, 0.        ],
       [1.40546511, 1.40546511, 0.        , 0.        , 0.        ,
        0.        , 2.09861229]])

In [49]:
from sklearn.preprocessing import normalize
normalize(Rachel, norm="l2")

array([[0.48624042, 0.48624042, 0.72604443, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.57735027,
        0.57735027, 0.        ],
       [0.48624042, 0.48624042, 0.        , 0.        , 0.        ,
        0.        , 0.72604443]])

In [45]:
norm_berry=np.linalg.norm(Rachel,2,0)
normed=[]
for i in range(7):
    Rachel[:,i]/norm_berry[i]
print(Rachel2)

[0. 0. 1.]


array([1.40546511, 0.        , 1.40546511])